apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: cloud-controller-manager
    tier: control-plane
  name: openstack-cloud-controller-manager
  namespace: kube-system
spec:
  containers:
    - name: openstack-cloud-controller-manager
      image: docker.io/mmsyhu/openstack-cloud-controller-manager:v1.24.0-22-gf75091d-dirty
      imagePullPolicy: IfNotPresent
      args:
        - /bin/openstack-cloud-controller-manager
        - --v=5
        - --cloud-config=/etc/kubernetes/cloud-config
        - --cloud-provider=openstack
        - --kubeconfig=/etc/kubernetes/admin.conf
        - --bind-address=127.0.0.1
        - --cluster-name=ike-prod-test03-ms-ike-prod-01
      volumeMounts:
        - mountPath: /etc/kubernetes
          name: k8s-certs
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ca-certs
          readOnly: true
      resources:
        requests:
          cpu: 200m
  hostNetwork: true
  securityContext:
    runAsUser: 0
  volumes:
    - hostPath:
        path: /etc/kubernetes
        type: DirectoryOrCreate
      name: k8s-certs
    - hostPath:
        path: /etc/ssl/certs
        type: DirectoryOrCreate
      name: ca-certs